kernel.spec: fix 'make scripts' for kernel-devel package
Upstream status: RHEL only

Running 'make scripts' in /usr/src/kernels/$VERSION triggers the
following error:

    scripts/selinux/genheaders/genheaders.c:19:10: fatal error:
    classmap.h: No such file or directory

Let's fix that by including the necessary two files from the
directory security/selinux/include/ in the kernel-devel package.
Once those files are added, another error is triggered:

    scripts/sortextable.c:31:10: fatal error: tools/be_byteshift.h:
    No such file or directory

Let's correct that error by adding two more files from tools/include/
to the kernel-devel package as well. This will get 'make scripts'
working.

This change adds 20K (before compression) to the kernel-devel package.

Signed-off-by: Brian Masney <bmasney@redhat.com>