(DO NOT MERGE) Revert "ARM: 9095/1: ARM64: Remove arm_pm_restart()"
This reverts commit ab6cef1d14475f1af33da99a6774626f73d278b6.

Temporary fix to compile error:
  /srv/source/drivers/power/reset/odroid-reboot.c: In function ‘odroid_restart_probe’:
  /srv/source/drivers/power/reset/odroid-reboot.c:141:3: error: ‘arm_pm_restart’
  undeclared (first use in this function); did you mean ‘alarm_restart’?
    141 |   arm_pm_restart = do_odroid_restart;
        |   ^~~~~~~~~~~~~~
        |   alarm_restart
  /srv/source/drivers/power/reset/odroid-reboot.c:141:3: note: each
  undeclared identifier is reported only once for each function it appears in

commit: 59541fb75ee4 "ODROID-COMMON: power:reset: Add odroid support"

Change-Id: Id81d2cb4c7a55e660e7158a8eb7937fff077abcf